<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hamburgueria.Application\Hamburgueria.Application.csproj" />
    <ProjectReference Include="..\Hamburgueria.Infrastructure\Hamburgueria.Infrastructure.csproj" />
    <PackageReference Include="MediatR" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>
</Project>
